spring:
    devtools:
        restart:
            enabled: true
    sql:
        init:
            mode: EMBEDDED
    datasource:
        url: jdbc:h2:mem:testdb;MODE=PostgreSQL
        username: sa
        password:
    jpa:
        open-in-view: false
    main:
        banner-mode: off

management:
    info:
        env:
            enabled: true
    endpoints:
        web:
            exposure:
                include: health,info
    endpoint:
        health:
            show-details: always
        info:
            enabled: true

info:
   app:
      name: Patient API
      version: 0.0.1

server:
    port: 443
    ssl:
        enabled: true
        key-store: classpath:keystore.jks
        key-store-password: password
        key-store-type: JKS
        trust-store: classpath:truststore.jks
        trust-store-password: password
        trust-store-type: JKS
        client-auth: need

logging:
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss.SSS} | client:%X{client_name} | %5p | %-40.40logger{39} | %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
