spring:
    config:
        activate:
            on-profile: local
    datasource:
        url: jdbc:postgresql://localhost:5432/api_development
        username: testuser
        password: testpassword
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    devtools:
        add-properties: false
